theme: jekyll-theme-minimal
title: [Sergio A. Mora Pardo, MSc (c)]
description: [Data Science and Analitycs.]
logo: [https://raw.githubusercontent.com/sergiomora03/sergiomora03.github.io/master/images/pp.jpg]
show_downloads: [true]
