title: sergiomora03.github.io
logo: /images/pp.jpg
description: Hi, I´m an enthusiast machine learning engineering and deep learning.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
