title: sergiomora03.github.io
logo: /images/pp.jpg
description: Hi, I am an enthusiast machine learning engineering and deep learning lover.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
